-- Wire custom badge icons (PNG files served from /badges/<slug>.png on afterroar.me).
-- Generated by scripts/build-badges.mjs.
-- Idempotent — safe to re-run.

UPDATE "PassportBadge"
SET "iconUrl" = '/badges/passport-pioneer.png'
WHERE "slug" = 'passport-pioneer';

UPDATE "PassportBadge"
SET "iconUrl" = '/badges/pollock-party-2026.png'
WHERE "slug" = 'pollock-party-2026';

UPDATE "PassportBadge"
SET "iconUrl" = '/badges/fugly-early-adopter.png'
WHERE "slug" = 'fugly-early-adopter';
